name: pw-comments
type: php
docroot: ""
no_project_mount: true
php_version: "8.2"
composer_version: "2"
webserver_type: apache-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames:
    - docs.pw-comments
    - v12.pw-comments
additional_fqdns: []
use_dns_when_possible: true
omit_containers:
    - dba
extra_services:
    - v12-data
host_db_port: "32682"
